src/WebApp/PresentersWebApp/Controllers/JobsController.cs
using Consumer.JobApiServices.Interfaces;
using Dto.Consumers;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;

namespace PresentersWebApp.Controllers
{
    public class JobsController : Controller
    {
        private readonly IConsumer Consumer;
        private readonly IConfiguration Configuration;
        public JobsController(IConsumer Consumer, IConfiguration Configuration) {
            this.Consumer = Consumer;
            this.Configuration = Configuration;
        }

        public IActionResult Index()
        {
            GenericResponse<List<JobDto>> response = new GenericResponse<List<JobDto>>() ;
            try {
                string baseUrl = Configuration.GetValue<string>("ServiceUrl");
                response = Consumer.Get<List<JobDto>>(baseUrl, "Job", "GetAll", string.Empty);
            } catch (Exception ex) {
                response.Item = new List<JobDto>();
                response.Message = ex.Message;
                response.Status = "FAILURE";
            }
            
            return View(response.Item);
        }

        [HttpGet("Edit")]
        public IActionResult Edit(int Id)
        {
            GenericResponse<JobDto> response = new GenericResponse<JobDto>();
            ViewBag.Message = string.Empty;
            ViewBag.ErrorMessage = string.Empty;
            try
            {
                string baseUrl = Configuration.GetValue<string>("ServiceUrl");
                response = Consumer.Get<JobDto>(baseUrl, "Job", "Get", Id.ToString());
            }
            catch (Exception ex)
            {
                response.Item = new JobDto();
                response.Message = ex.Message;
                response.Status = "FAILURE";
            }

            return View(response.Item);
        }

        [HttpPost("Edit")]
        public IActionResult EditPost(JobDto data)
        {
            GenericResponse<JobDto> response = new GenericResponse<JobDto>();
            try
            {
                if (string.IsNullOrEmpty(data.Job))
                {
                    ViewBag.Message = string.Empty;
                    ViewBag.ErrorMessage = "The Job can't be empty";
                    return View("Edit", data);
                }

                string baseUrl = Configuration.GetValue<string>("ServiceUrl");
                response = Consumer.PostWithJson<JobDto, JobDto>(baseUrl, "Job", "Update", data);
                ViewBag.Message = "It's successful edited";
                ViewBag.ErrorMessage = string.Empty;
            }
            catch (Exception ex)
            {
                response.Item = new JobDto();
                response.Message = ex.Message;
                response.Status = "FAILURE";
                ViewBag.ErrorMessage = ex.Message;
                ViewBag.Message = string.Empty;
            }
            
            return View("Edit",response.Item);
        }

        [HttpGet("Create")]
        public IActionResult Create()
        {
            ViewBag.Message = string.Empty;
            ViewBag.ErrorMessage = string.Empty;
            return View("Create", new JobDto() { 
                CreatedAt = DateTime.Now
            });
        }

        [HttpPost("Create")]
        public IActionResult CreatePost(JobDto data)
        {
            GenericResponse<JobDto> response = new GenericResponse<JobDto>();
            try
            {
                if (string.IsNullOrEmpty(data.Job))
                {
                    ViewBag.Message = string.Empty;
                    ViewBag.ErrorMessage = "The Job can't be empty";
                    return View("Create", data);
                }

                string baseUrl = Configuration.GetValue<string>("ServiceUrl");
                response = Consumer.PostWithJson<JobDto, JobDto>(baseUrl, "Job", "Save", data);
                ViewBag.Message = "It's successful created";
                ViewBag.ErrorMessage = string.Empty;
            }
            catch (Exception ex)
            {
                response.Item = new JobDto();
                response.Message = ex.Message;
                response.Status = "FAILURE";
                ViewBag["ErrorMessage"] = ex.Message;
                ViewBag["Message"] = string.Empty;
            }            

            return View("Create", response.Item);
        }

        [HttpPost("Delete")]
        public IActionResult Delete(int JobId)
        {
            GenericResponse<JobDto> deleteResponse = new GenericResponse<JobDto>();
            try
            {

                string baseUrl = Configuration.GetValue<string>("ServiceUrl");
                deleteResponse = Consumer.PostWithJson<JobDto, JobDto>(baseUrl, "Job", "Delete", new JobDto() { JobId = JobId });
            }
            catch (Exception ex)
            {
                deleteResponse.Item = new JobDto();
                deleteResponse.Message = ex.Message;
                deleteResponse.Status = "FAILURE";
            }

            GenericResponse<List<JobDto>> response = new GenericResponse<List<JobDto>>();
            try
            {
                string baseUrl = Configuration.GetValue<string>("ServiceUrl");
                response = Consumer.Get<List<JobDto>>(baseUrl, "Job", "GetAll", string.Empty);
            }
            catch (Exception ex)
            {
                response.Item = new List<JobDto>();
                response.Message = ex.Message;
                response.Status = "FAILURE";
            }

            return View("Index", response.Item);
        }
    }
}

src/WebApp/PresentersWebApp/Views/Jobs/Create.cshtml
@model Dto.Consumers.JobDto
@{
    Layout = null;
    var ValueExpiresAt = @Model.ExpiresAt != null ? @Model.ExpiresAt.Value.ToString("yyyy-MM-ddThh:mm") : "n/a";
}
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>

    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>

    <div class="text-center"><H1></H1>Jobs Create</div>
    <hr />
    <div class="container-fluid">
        <div class="col-md-12">
            <form action="Create" method="post" name="data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Job" class="control-label">Job</label>
                    <input name="Job" class="form-control" value="@Model.Job" />
                    <span asp-validation-for="Job" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="JobTitle" class="control-label">JobTitle</label>
                    <input name="JobTitle" class="form-control" value="@Model.JobTitle" />
                    <span asp-validation-for="JobTitle" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label">Description</label>
                    <input name="Description" class="form-control" value="@Model.Description" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="CreatedAt" class="control-label">CreatedAt</label>
                    <input name="CreatedAt" type="datetime-local" class="form-control" value="@Model.CreatedAt.ToString("yyyy-MM-ddThh:mm")" />
                    <span asp-validation-for="CreatedAt" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ExpiresAt" class="control-label">ExpiresAt</label>
                    <input name="ExpiresAt" type="datetime-local" class="form-control" value="@ValueExpiresAt" />
                    <span asp-validation-for="ExpiresAt" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
            </form>
            @if (!string.IsNullOrEmpty(ViewBag.Message))
            {
                <span class="alert alert-info">@ViewBag.Message</span>
            }
            @if (!string.IsNullOrEmpty(ViewBag.ErrorMessage))
            {
                <span class="alert alert-danger">@ViewBag.ErrorMessage</span>
            }
        </div>
        <br/>
        <div>
            <a href="/">Back to List</a>
        </div>
    </div>

    
    <script>
        $("#ErrorMessage").fadeOut(15000);
        $("#Message").fadeOut(15000);
        
    </script>
</body>
</html>

src/WebApp/PresentersWebApp/Views/Jobs/Edit.cshtml
@model Dto.Consumers.JobDto
@{
    Layout = null;
    var ValueExpiresAt = @Model.ExpiresAt != null ? @Model.ExpiresAt.Value.ToString("yyyy-MM-ddThh:mm") : "n/a";
}

<!DOCTYPE html>

<html>
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>

</head>
<body>

    <div class="text-center"><H1></H1>Jobs Edit</div>
<hr />
<div class="container-fluid">
    <div class="col-md-12">
        <form action="Edit" method="post" name="data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" name="JobId" class="form-control" value="@Model.JobId" />
            <div class="form-group">
                <label asp-for="Job" class="control-label">Job</label>
                <input name="Job" class="form-control" value="@Model.Job" />
                <span asp-validation-for="Job" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="JobTitle" class="control-label">JobTitle</label>
                <input name="JobTitle" class="form-control" value="@Model.JobTitle" />
                <span asp-validation-for="JobTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label">Description</label>
                <input name="Description" class="form-control" value="@Model.Description" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedAt" class="control-label">CreatedAt</label>
                <input name="CreatedAt" type="datetime-local" class="form-control" value="@Model.CreatedAt.ToString("yyyy-MM-ddThh:mm")" />
                <span asp-validation-for="CreatedAt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ExpiresAt" class="control-label">ExpiresAt</label>
                <input name="ExpiresAt" type="datetime-local" class="form-control" value="@ValueExpiresAt" />
                <span asp-validation-for="ExpiresAt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
        @if (!string.IsNullOrEmpty(ViewBag.Message))
        {
            <span class="alert alert-info" id="Message">@ViewBag.Message</span>
        }
        @if (!string.IsNullOrEmpty(ViewBag.ErrorMessage))
        {
            <span class="alert alert-danger" id="ErrorMessage">@ViewBag.ErrorMessage</span>
        }
    </div>
    <br />
    <div>
        <a href="/">Back to List</a>
    </div>
</div>


</body>
</html>

src/WebApp/PresentersWebApp/Views/Jobs/Index.cshtml
@model IEnumerable<Dto.Consumers.JobDto>

@{
    Layout = null;
}

<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <style>
        a{color:white;}
    </style>
    <title>Jobs CRUD</title>
</head>
<body>

    <div class="container-fluid">

        <div class="text-center"><H1></H1>Jobs Board</div>
        <li class="btn btn-info">@Html.ActionLink("Create", "Create", "Jobs")</li>
        <hr />
        <div class="col-md-12">
            <div class="col-md-12 col-lg-12 col-sm-12">
                <table class="table">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.JobId)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Job)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.JobTitle)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Description)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.CreatedAt)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.ExpiresAt)
                            </th>
                            <th><span class="glyphicon glyphicon-pencil"></span></th>
                            <th><span class="glyphicon glyphicon-trash"></span></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.JobId)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Job)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.JobTitle)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Description)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.CreatedAt)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ExpiresAt)
                                </td>
                                <td>
                                    <li class="btn btn-success">@Html.ActionLink("Edit", "Edit", "Jobs", new { id = item.JobId })</li>
                                </td>
                                <td>
                                    <form action="Delete" method="post" onsubmit="return SubmitConfirmation()">
                                        <input type="hidden" name="JobId" class="form-control" value="@item.JobId" />
                                        <input type="submit" value="Delete" class="btn btn-danger" />
                                    </form>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>

    </div>
    <script>
        function SubmitConfirmation(e) {
            
            if (!confirm('Do you want to remove?')) {
                return false;
            }
        }
    </script>
</body>
</html>